### PR TITLE
New package: warhol (was grc)

### PR DESCRIPTION
**Pull request by sonnius**
Adding new plugin: grc

This colorises various commands using grc

### CODE REVIEW

**Comment by molovo** [comment]
@sonnius thanks for the PR. Your addition looks good, but could you please rename the package 'warhol' since that's the name of the underlying script? Might cause confusion otherwise.

**Comment by sonnius** [comment]
Molovo,

Thanks for the feedback, I've updated the package name to: warhol

**Comment by molovo** [comment]
@sonnius thanks, but you'll need to rename the file as well to match. Sorry if that wasn't clear.

**Comment by molovo** [comment]
Awesome. Merging now. Thanks for contributing.

**Pull request merged**
